[tool.poetry]
name = "createpersoncard"
version = "0.1.0"
description = ""
authors = ["VKon <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Faker = "^8.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
